import { lazy } from 'react'
export default [
  {
    path: '/components/icon',
    title: 'Icon',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/icon')),
    desc: '图标',
    exact: true,
  },
  {
    path: '/components/layout',
    title: 'Layout',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/layout')),
    desc: '布局',
    exact: true,
  },
  {
    path: '/components/button',
    title: 'Button',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/button')),
    desc: '按钮',
    exact: true,
  },
  {
    path: '/components/dialog',
    title: 'Dialog',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/dialog')),
    desc: '对话框',
    exact: true,
  },
  {
    path: '/components/popover',
    title: 'Popover',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/popover')),
    desc: '弹出框',
    exact: true,
  },
  {
    path: '/components/tooltip',
    title: 'Tooltip',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/tooltip')),
    desc: '文字提示',
    exact: true,
  },
  {
    path: '/components/input',
    title: 'Input',
    desc: '输入框',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/input/index')),
    exact: true,
  },
  {
    path: '/components/foldcard',
    title: 'Foldcard',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/foldcard')),
    desc: '折叠卡片',
    exact: true,
  },
  {
    path: '/components/radio',
    title: 'Radio',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/radio')),
    desc: '单选框',
    exact: true,
  },
  {
    path: '/components/checkbox',
    title: 'Checkbox',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/checkbox')),
    desc: '多选框',
    exact: true,
  },
  {
    path: '/components/progress',
    title: 'Progress',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/progress')),
    desc: '进度条',
    exact: true,
  },
  {
    path: '/components/message',
    title: 'Message',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/message')),
    desc: '消息提示',
    exact: true,
  },
  {
    path: '/components/loading',
    title: 'Loading',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/loading')),
    desc: '加载',
    exact: true,
  },
  {
    path: '/components/drawer',
    title: 'Drawer',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/drawer')),
    desc: '抽屉',
    exact: true,
  },
  {
    path: '/components/badge',
    title: 'Badge',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/badge')),
    desc: '徽标',
    exact: true,
  },
  {
    path: '/components/skeleton',
    title: 'Skeleton',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/skeleton')),
    desc: '骨架屏',
    exact: true,
  },
  {
    path: '/components/card',
    title: 'Card',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/card')),
    desc: '卡片',
    exact: true,
  },
  {
    path: '/components/menu',
    title: 'Menu',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/menu')),
    desc: '菜单',
    exact: true,
  },
  {
    path: '/components/collapse',
    title: 'Collapse',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/collapse')),
    desc: '折叠面板',
    exact: true,
  },
  {
    path: '/components/divider',
    title: 'Divider',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/divider')),
    desc: '分割线',
    exact: true,
  },
  {
    path: '/components/text-link',
    title: 'TextLink',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/text-link')),
    desc: '文字链接',
    exact: true,
  },
  {
    path: '/components/pagination',
    title: 'Pagination',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/pagination')),
    desc: '分页',
    exact: true,
  },
  // {
  //   path: '/components/tabs',
  //   title: 'Tabs',
  //   component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/tabs')),
  //   desc: '标签页',
  //   exact: true,
  // },
  {
    path: '/components/back-top',
    title: 'BackTop',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/back-top')),
    desc: '回到顶部',
    exact: true,
  },
  {
    path: '/components/image',
    title: 'Image',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/image')),
    desc: '图片',
    exact: true,
  },
  {
    path: '/components/switch',
    title: 'Switch',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/switch')),
    desc: '开关',
    exact: true,
  },
  {
    path: '/components/result',
    title: 'Result',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/result')),
    desc: '结果',
    exact: true,
  },
  {
    path: '/components/date-picker',
    title: 'DatePicker',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/date-picker')),
    desc: '时间选择器',
    exact: true,
  },
  {
    path: '/components/carousel',
    title: 'Carousel',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/carousel')),
    desc: '走马灯',
    exact: true,
  },
  {
    path: '/components/dropdown',
    title: 'Dropdown',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/dropdown')),
    desc: '下拉菜单',
    exact: true,
  },
  {
    path: '/components/select',
    title: 'Select',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/select')),
    desc: '选择框',
    exact: true,
  },
  {
    path: '/components/test',
    title: 'Test',
    component: lazy(() => import(/* webpackMode: "lazy" */ '../pages/test')),
    desc: '测试页',
    exact: true,
  },
]
